#!/bin/sh

# Load nvm and use the correct Node.js version if nvm is installed
export NVM_DIR="$HOME/.nvm"
if [ -s "$NVM_DIR/nvm.sh" ]; then
    . "$NVM_DIR/nvm.sh"
    nvm use
fi

# Skip pre-commit hook for VS Code Git integration
if [ "$GIT_EDITOR" = "code --wait" ]; then
    exit 0
fi

npx lint-staged
